/* Staff UI strings. Indonesian is the default; English mirrors it.
   Keep copy short: a label or one sentence, never a paragraph. */

export type Lang = "id" | "en";

const id: Record<string, string> = {
  // common
  "common.loading": "Memuat…",
  "common.save": "Simpan",
  "common.saved": "Tersimpan",
  "common.cancel": "Batal",
  "common.close": "Tutup",
  "common.add": "Tambah",
  "common.edit": "Ubah",
  "common.delete": "Hapus",
  "common.search": "Cari",
  "common.none": "Tidak ada",
  "common.never": "belum pernah",
  "common.you": "Anda",
  "common.on": "aktif",
  "common.off": "nonaktif",
  "common.today": "Hari ini",
  "common.thisMonth": "Bulan ini",
  "common.table": "Tabel",
  "common.chart": "Grafik",
  "common.readOnly": "Hanya baca.",
  "common.simulated": "simulasi",
  "common.theme": "Ganti mode terang/gelap",
  "common.language": "Bahasa",

  // time
  "time.justNow": "baru saja",
  "time.minutes": "{n} mnt",
  "time.hours": "{n} j",
  "time.days": "{n} h",
  "time.windowClosed": "jendela tertutup",
  "time.windowLeft": "sisa {h}j {m}m",

  // nav
  "nav.conversations": "Percakapan",
  "nav.outreach": "Penjangkauan",
  "nav.reports": "Laporan",
  "nav.admin": "Admin",
  "nav.inbox": "Kotak masuk",
  "nav.cases": "Kasus",
  "nav.contacts": "Kontak",
  "nav.simulator": "Simulator",
  "nav.broadcasts": "Broadcast",
  "nav.dashboard": "Dasbor",
  "nav.audit": "Log audit",
  "nav.settings": "Pengaturan",
  "nav.knowledge": "Pengetahuan",
  "nav.signOut": "Keluar",
  "nav.tagline": "Pendamping TBC",
  "role.admin": "Admin",
  "role.agent": "Agen",
  "role.reviewer": "Peninjau",

  // login
  "login.subtitle": "Masuk staf",
  "login.email": "Email",
  "login.password": "Kata sandi",
  "login.submit": "Masuk",
  "login.submitting": "Masuk…",
  "login.prototype": "Prototipe — hanya data uji.",
  "login.code": "Kode verifikasi",
  "login.codeHint": "Buka aplikasi autentikator dan masukkan 6 angka.",
  "account.title": "Akun saya",
  "account.twofa": "Verifikasi dua langkah",
  "account.twofaOn": "Aktif. Setiap masuk perlu kode dari aplikasi autentikator.",
  "account.twofaOff": "Belum aktif. Tambahkan kode dari ponsel saat masuk, agar akun lebih aman.",
  "account.setup": "Aktifkan",
  "account.scan": "Pindai kode ini dengan Google Authenticator, Authy, atau aplikasi serupa. Lalu masukkan 6 angka yang muncul.",
  "account.manual": "Tidak bisa memindai? Masukkan kunci ini:",
  "account.confirm": "Konfirmasi",
  "account.disable": "Matikan",
  "account.disableHint": "Masukkan kata sandi untuk mematikan verifikasi dua langkah.",
  "account.password": "Ganti kata sandi",
  "account.current": "Kata sandi sekarang",
  "account.new": "Kata sandi baru (min. 10)",
  "account.change": "Ganti",
  "account.changed": "Kata sandi diganti. Sesi lain sudah dikeluarkan.",
  "staff.reset2fa": "Reset",
  "staff.reset2faConfirm": "Matikan verifikasi dua langkah untuk {name}? Mereka bisa masuk hanya dengan kata sandi.",

  // channels & severity
  "channel.simulated": "simulasi",
  "sev.low": "Rendah",
  "sev.high": "Tinggi",
  "sev.emergency": "Darurat",
  "cat.emergency": "darurat",
  "cat.self_harm": "menyakiti diri",
  "cat.adverse_drug": "efek samping obat",
  "cat.adherence": "pengobatan terhenti",
  "cat.budget": "anggaran AI",
  "cat.bot_error": "bot gagal",
  "cat.screening": "skrining",
  "mode.human": "Ditangani staf",

  // inbox list
  "inbox.searchPlaceholder": "Cari",
  "inbox.allChannels": "Semua kanal",
  "inbox.anyStatus": "Semua status",
  "inbox.open": "Terbuka",
  "inbox.resolved": "Selesai",
  "inbox.anyFlag": "Semua tanda",
  "inbox.flagged": "Ditandai",
  "inbox.highUp": "Tinggi ke atas",
  "inbox.emergency": "Darurat",
  "inbox.botAndStaff": "Bot & staf",
  "inbox.bot": "Bot",
  "inbox.staffHandling": "Ditangani staf",
  "inbox.optedOut": "STOP",
  "inbox.empty": "Belum ada percakapan.",
  "inbox.select": "Pilih percakapan",
  "inbox.filterChannel": "Kanal",
  "inbox.filterStatus": "Status",
  "inbox.filterFlag": "Tanda",
  "inbox.filterMode": "Mode",
  "inbox.filterLabel": "Label",
  "inbox.anyLabel": "Semua label",

  // thread
  "thread.assignedTo": "ditangani {name}",
  "thread.unassigned": "belum ditangani",
  "thread.bot": "Bot",
  "thread.staff": "Staf",
  "thread.modeHint": "Mode staf: bot diam",
  "thread.summary": "Ringkasan AI",
  "thread.summarising": "Meringkas…",
  "thread.assignMe": "Ambil",
  "thread.resolve": "Selesaikan",
  "thread.reopen": "Buka lagi",
  "thread.replyPlaceholderBot": "Balas sebagai staf (bot akan berhenti)",
  "thread.replyPlaceholder": "Balas sebagai staf",
  "thread.notePlaceholder": "Catatan internal, tidak dikirim ke pasien",
  "thread.send": "Kirim",
  "thread.addNote": "Simpan catatan",
  "thread.sendHint": "Ctrl+Enter untuk kirim · ketik / untuk balasan tersimpan",
  "thread.optedOut": "Kontak ini membalas STOP. Pesan tidak bisa dikirim.",
  "thread.tabReply": "Balas",
  "thread.tabNote": "Catatan",
  "thread.suggest": "Saran AI",
  "thread.suggesting": "Menyusun…",
  "thread.attach": "Lampirkan file",
  "thread.labels": "Label",
  "thread.addLabel": "Tambah label",
  "summary.title": "Ringkasan untuk staf",
  "summary.footer": "Dibuat AI ({model}, {cost}). Cek percakapan sebelum bertindak.",

  // message bubble
  "msg.bot": "Onti (bot)",
  "msg.staff": "Staf",
  "msg.broadcast": "Broadcast",
  "msg.note": "Catatan",
  "msg.notDelivered": "Tidak terkirim: {error}",
  "msg.flaggedBy": "Ditandai oleh {reason}",
  "msg.sources": "Sumber {docs}",
  "msg.tokens": "{n} token",
  "msg.transcript": "Transkrip",
  "msg.openFile": "Buka file",

  // contact panel
  "contact.since": "Kontak sejak {date}",
  "contact.details": "Detail",
  "contact.phone": "Telepon",
  "contact.messages": "Pesan",
  "contact.active": "Aktif",
  "contact.optedOut": "Berhenti (STOP)",
  "contact.broadcasts": "Broadcast",
  "contact.subscribed": "Berlangganan",
  "contact.notSubscribed": "Tidak berlangganan",
  "contact.channels": "Kanal",
  "contact.cases": "Kasus",
  "contact.noCases": "Tidak ada kasus.",
  "contact.notes": "Catatan",
  "contact.journey": "Perjalanan pasien",
  "contact.treatmentMonth": "Bulan pengobatan ke-{n}",

  // cases
  "cases.filterActive": "Terbuka & diambil",
  "cases.filterOpen": "Belum diambil",
  "cases.filterClaimed": "Diambil",
  "cases.filterResolved": "Selesai",
  "cases.filterAll": "Semua kasus",
  "cases.status.OPEN": "Belum diambil",
  "cases.status.CLAIMED": "Diambil",
  "cases.status.RESOLVED": "Selesai",
  "cases.empty": "Tidak ada kasus.",
  "cases.select": "Pilih kasus",
  "cases.title": "Kasus #{id}",
  "cases.opened": "dibuka {date}",
  "cases.openConversation": "Buka percakapan",
  "cases.claim": "Ambil",
  "cases.unclaim": "Lepas",
  "cases.resolveKeep": "Selesai, tetap staf",
  "cases.resolveBot": "Selesai & kembali ke bot",
  "cases.contact": "Kontak",
  "cases.channel": "Kanal",
  "cases.assigned": "Ditangani",
  "cases.nobody": "Belum ada",
  "cases.mode": "Mode",
  "cases.trigger": "Pesan pemicu",
  "cases.notes": "Catatan",
  "cases.noNotes": "Belum ada catatan.",
  "cases.notePlaceholder": "Tambah catatan",
  "cases.addNote": "Tambah",

  // contacts
  "contacts.search": "Cari nama, telepon, atau ID",
  "contacts.timeline": "Semua pesan lintas kanal",
  "contacts.openConversation": "Buka percakapan {channel}",
  "contacts.consent": "Persetujuan",
  "contacts.recordConsent": "Catat persetujuan broadcast",
  "contacts.revokeConsent": "Cabut persetujuan broadcast",
  "contacts.consentRecorded": "Persetujuan dicatat",
  "contacts.notesPlaceholder": "Catatan tentang kontak ini",
  "contacts.saveNotes": "Simpan catatan",
  "contacts.merge": "Gabungkan kontak ganda",
  "contacts.chooseContact": "Pilih kontak",
  "contacts.mergeButton": "Gabungkan",
  "contacts.mergeHint": "Kanal, percakapan, kasus, dan persetujuan pindah ke sini.",
  "contacts.merged": "Kontak digabung",
  "contacts.select": "Pilih kontak",
  "contacts.subscribed": "berlangganan",
  "contacts.optedOut": "STOP",

  // simulator
  "sim.intro": "Chat sebagai pengguna uji. Tidak ada yang dikirim ke Meta.",
  "sim.channel": "Kanal",
  "sim.userId": "ID pengguna",
  "sim.name": "Nama tampilan",
  "sim.quick": "Pesan cepat",
  "sim.empty": "Kirim pesan untuk mulai.",
  "sim.placeholder": "Ketik sebagai pengguna…",
  "sim.openInbox": "Buka di kotak masuk →",
  "sim.staffNotice": "Staf sedang menangani chat ini, jadi bot diam.",
  "sim.handBack": "Kembalikan ke bot",
  "sim.s.normal": "Pertanyaan biasa",
  "sim.s.english": "Pertanyaan bahasa Inggris",
  "sim.s.mild": "Efek samping ringan",
  "sim.s.drug": "Efek samping berat",
  "sim.s.emergency": "Darurat",
  "sim.s.selfharm": "Menyakiti diri",
  "sim.s.adherence": "Berhenti berobat",
  "sim.s.screening": "Skrining TBC",
  "sim.s.subscribe": "Berlangganan (LANGGANAN)",
  "sim.s.stop": "Berhenti (STOP)",
  "sim.s.start": "Mulai lagi (MULAI)",
  "sim.staff": "Staf",
  "sim.record": "Rekam pesan suara",
  "sim.stopRecording": "Berhenti & kirim",
  "sim.recording": "Merekam…",
  "sim.micDenied": "Mikrofon tidak bisa dipakai di browser ini.",

  // dashboard
  "dash.convToday": "Percakapan hari ini",
  "dash.thisMonth": "{n} bulan ini",
  "dash.firstBot": "Respons pertama · bot",
  "dash.firstStaff": "Respons pertama · staf",
  "dash.replies": "{n} balasan · 30 hari",
  "dash.contacts": "Kontak",
  "dash.contactsSub": "{sub} berlangganan · {out} STOP",
  "dash.caseEmergency": "Kasus darurat",
  "dash.caseHigh": "Kasus tinggi",
  "dash.caseLow": "Kasus rendah",
  "dash.costs": "Biaya bulan ini",
  "dash.aiSpend": "Biaya AI",
  "dash.noLimit": "tanpa batas",
  "dash.ok": "Aman",
  "dash.warn": "Mendekati batas",
  "dash.over": "Batas tercapai",
  "dash.calls": "{n} panggilan AI · {failed} gagal",
  "dash.fallbackModel": "di 100%: model lebih murah",
  "dash.fallbackFixed": "di 100%: balasan tetap",
  "dash.waTemplates": "Template WhatsApp",
  "dash.waSent": "{n} pesan WhatsApp terkirim",
  "dash.byChannel": "Percakapan aktif per kanal",
  "dash.conversations": "{n} percakapan",
  "dash.programme": "Program TBC",
  "dash.flagsWeek": "Tanda risiko, 8 minggu",
  "dash.adherence": "Kepatuhan minum obat",
  "dash.adherenceSub": "{taken} dari {total} pengingat dijawab sudah minum · 30 hari",
  "dash.journey": "Tahap pasien",
  "dash.screenings": "Skrining",
  "dash.screeningsSub": "{n} disarankan periksa · 30 hari",
  "dash.export": "Unduh CSV",

  // settings
  "settings.channels": "Kanal",
  "settings.botSafety": "Bot, keamanan & biaya",
  "settings.staff": "Staf",
  "settings.replies": "Balasan tersimpan",
  "settings.labels": "Label",
  "settings.hours": "Jam layanan",
  "settings.security": "Keamanan akun",
  "ch.connected": "Terhubung",
  "ch.notConfigured": "Belum diatur",
  "ch.off": "Nonaktif",
  "ch.webhook": "Webhook",
  "ch.missing": "Belum diisi: {list}",
  "ch.learned": "{key} dari webhook: {value}",
  "ch.lastWebhook": "Webhook terakhir: {when}",
  "ch.test": "Tes token",
  "ch.checking": "Memeriksa…",
  "ch.tokenOk": "Token berfungsi: {phone}. Pengiriman: {sending}",
  "ch.failed": "Gagal: {error}",
  "ch.llm": "LLM",
  "ch.answers": "Jawaban",
  "ch.classifier": "Klasifikasi",
  "ch.email": "Email peringatan",
  "ed.unsaved": "Ada perubahan belum disimpan",
  "ed.saved": "Semua tersimpan",
  "ed.reset": "Kembalikan bawaan",
  "ed.rules": "Kata kunci keamanan",
  "ed.rulesHint": "Satu kata atau frasa per baris. Selalu berjalan.",
  "ed.group.Bot": "Bot",
  "ed.group.Safety": "Keamanan",
  "ed.group.Consent & keywords": "Persetujuan & kata kunci",
  "ed.group.Limits & budget": "Batas & anggaran",
  "ed.group.WhatsApp pricing": "Tarif WhatsApp",
  "ed.group.Office hours": "Jam layanan",
  "ed.group.Reminders": "Pengingat obat",
  "staff.email": "Email",
  "staff.name": "Nama",
  "staff.role": "Peran",
  "staff.status": "Status",
  "staff.deactivate": "Nonaktifkan",
  "staff.activate": "Aktifkan",
  "staff.add": "Tambah staf",
  "staff.password": "Kata sandi (min. 10)",
  "staff.added": "Staf ditambahkan",
  "staff.roleUpdated": "Peran diubah",
  "staff.twofa": "2FA",
  "ed.discard": "Buang",
  "day.1": "Sen",
  "day.2": "Sel",
  "day.3": "Rab",
  "day.4": "Kam",
  "day.5": "Jum",
  "day.6": "Sab",
  "day.7": "Min",
  "set.away_message.hint": "{jam} diganti jam layanan.",
  "ed.language": "Versi bahasa",
  "set.persona_prompt": "Instruksi bot (persona)",
  "set.model_answer": "Model jawaban",
  "set.model_classifier": "Model klasifikasi",
  "set.history_turns": "Riwayat chat yang dibaca",
  "set.retrieval_k": "Jumlah kutipan pengetahuan",
  "set.max_input_chars": "Maks. karakter pesan masuk",
  "set.max_output_tokens": "Maks. token jawaban",
  "set.max_reply_chars": "Maks. karakter balasan",
  "set.classifier_enabled": "Klasifikasi risiko dengan AI",
  "set.safety_emergency": "Balasan darurat",
  "set.safety_self_harm": "Balasan menyakiti diri",
  "set.safety_adverse_drug": "Balasan efek samping obat",
  "set.safety_adherence": "Balasan berhenti berobat",
  "set.safety_other": "Balasan risiko lain",
  "set.consent_notice": "Pemberitahuan privasi (pesan pertama)",
  "set.optout_confirm": "Konfirmasi STOP",
  "set.optin_confirm": "Konfirmasi MULAI",
  "set.subscribe_confirm": "Konfirmasi LANGGANAN",
  "set.non_text_reply": "Balasan untuk foto/stiker",
  "set.monthly_budget_idr": "Anggaran AI per bulan (Rp)",
  "set.budget_alert_ratio": "Peringatan anggaran di (0–1)",
  "set.budget_fallback_mode": "Jika anggaran habis",
  "set.budget_fallback_reply": "Balasan tetap (anggaran habis / bot gagal)",
  "set.daily_message_cap": "Batas balasan bot per kontak per hari",
  "set.daily_cap_reply": "Balasan saat batas harian tercapai",
  "set.rate_limit_count": "Batas pesan beruntun",
  "set.rate_limit_window_minutes": "Dalam rentang (menit)",
  "set.rate_limit_reply": "Balasan saat terlalu cepat",
  "set.wa_rate_marketing_idr": "Tarif template marketing (Rp)",
  "set.wa_rate_utility_idr": "Tarif template utility (Rp)",
  "set.wa_free_tier_messages": "Kuota gratis per bulan",
  "set.office_hours_enabled": "Pakai jam layanan",
  "set.office_days": "Hari layanan",
  "set.office_open": "Buka",
  "set.office_close": "Tutup",
  "set.away_message": "Pesan di luar jam layanan",
  "set.reminder_enabled": "Kirim pengingat obat",
  "set.reminder_time": "Jam pengingat bawaan",
  "set.reminder_text": "Isi pengingat",
  "set.reminder_template": "Template WhatsApp (di luar 24 jam)",
  "set.missed_followup_hours": "Tindak lanjut jika belum dijawab (jam)",
  "set.missed_case_after": "Buat kasus setelah terlewat (kali)",
  "set.missed_followup": "Pesan tindak lanjut dosis terlewat",
  "set.transcribe_voice": "Transkrip pesan suara",
  "choice.classifier_model": "Pakai model lebih murah",
  "choice.fixed_reply": "Balasan tetap + kasus",
  "replies.shortcut": "Pintasan",
  "replies.title": "Judul",
  "replies.body": "Isi balasan",
  "replies.hint": "Ketik / di kotak balasan untuk memakai. {nama} diganti nama kontak.",
  "replies.empty": "Belum ada balasan tersimpan.",
  "replies.add": "Tambah balasan",
  "labels.placeholder": "Nama label baru",
  "labels.empty": "Belum ada label.",
  "labels.deleteConfirm": "Hapus label \"{name}\" dari semua percakapan?",

  // knowledge
  "kb.articles": "Artikel",
  "kb.gaps": "Belum terjawab",
  "kb.new": "Artikel baru",
  "kb.hidden": "disembunyikan",
  "kb.visible": "Dipakai bot",
  "kb.titlePlaceholder": "Judul artikel",
  "kb.hint": "Paragraf pertama jadi ringkasan. Pakai ## untuk subjudul.",
  "kb.deleteConfirm": "Hapus artikel \"{title}\"?",
  "kb.pending": "Ada perubahan yang belum diterbitkan",
  "kb.updating": "Memperbarui pengetahuan bot…",
  "kb.upToDate": "Diterbitkan {date}",
  "kb.failed": "Gagal memperbarui: {error}",
  "kb.publish": "Terbitkan",
  "kb.gapsIntro": "Pertanyaan yang belum bisa dijawab bot dari artikel. Tambahkan jawabannya ke artikel, lalu tandai selesai.",
  "kb.noGaps": "Tidak ada pertanyaan yang belum terjawab.",
  "kb.done": "Selesai",
  "kb.ignore": "Abaikan",

  // patient journey & tasks
  "nav.patients": "Pasien",
  "nav.tasks": "Tugas",
  "stage.none": "Bukan pasien",
  "stage.suspect": "Terduga",
  "stage.testing": "Pemeriksaan",
  "stage.treatment": "Pengobatan",
  "stage.completed": "Selesai",
  "stage.lost": "Putus berobat",
  "journey.title": "Perjalanan pasien",
  "journey.stage": "Tahap",
  "journey.month": "Bulan ke-{n} dari {total}",
  "journey.start": "Mulai berobat",
  "journey.months": "Lama (bulan)",
  "journey.puskesmas": "Puskesmas",
  "journey.kader": "Kader",
  "journey.none": "Belum ada",
  "journey.reminder": "Pengingat obat",
  "journey.last14": "Minum obat, 14 hari",
  "journey.taken": "Diminum",
  "journey.missed": "Terlewat",
  "journey.noReply": "Tidak ada data",
  "journey.tasks": "Tugas",
  "board.empty": "Belum ada pasien. Atur tahapnya dari panel kontak di kotak masuk atau halaman Kontak.",
  "board.week": "{taken}/{total} diminum minggu ini",
  "board.tasks": "{n} tugas",
  "board.month": "Bulan ke-{n}",
  "tasks.mine": "Tugas saya",
  "tasks.all": "Semua",
  "tasks.done": "Selesai",
  "tasks.overdue": "Terlambat",
  "tasks.today": "Hari ini",
  "tasks.upcoming": "Mendatang",
  "tasks.noDate": "Tanpa tanggal",
  "tasks.empty": "Tidak ada tugas.",
  "tasks.new": "Tugas baru",
  "tasks.titlePlaceholder": "Apa yang perlu dilakukan?",
  "tasks.kind.call": "Telepon",
  "tasks.kind.visit": "Kunjungan rumah",
  "tasks.kind.other": "Lainnya",
  "tasks.due": "Tenggat",
  "tasks.assignee": "Untuk",
  "tasks.unassigned": "Belum ditugaskan",
  "tasks.complete": "Selesai",
  "tasks.outcome": "Hasilnya? (opsional)",
  "tasks.add": "Tambah",
  "tasks.auto": "otomatis",
  "tasks.reopen": "Buka lagi",
  "tasks.contact": "Kontak (opsional)",
  "set.reminder_taken": "Balasan jika sudah minum",
  "set.reminder_missed": "Balasan jika belum minum",
  "set.reminder_text.hint": "{nama} diganti nama depan kontak. Tombol Sudah / Belum ditambahkan otomatis.",
  "set.reminder_template.hint": "Nama template WhatsApp yang disetujui, untuk pasien yang tidak chat dalam 24 jam. Kosong = hari itu dilewati.",

  // audit
  "audit.intro": "Siapa melihat, membalas, mengubah, atau mengirim apa.",
  "audit.all": "Semua aksi",
  "audit.when": "Waktu",
  "audit.who": "Siapa",
  "audit.action": "Aksi",
  "audit.target": "Target",
  "audit.details": "Detail",

  // broadcasts
  "bc.new": "Broadcast baru",
  "bc.template": "Template",
  "bc.chooseTemplate": "Pilih template yang disetujui",
  "bc.varHint": "teks, atau {{name}} untuk nama kontak",
  "bc.campaignName": "Nama kampanye",
  "bc.estimate": "Hitung biaya",
  "bc.sendTo": "Kirim ke {n}",
  "bc.recipients": "Penerima",
  "bc.cost": "Perkiraan biaya",
  "bc.rate": "Tarif {cat}",
  "bc.thisMonth": "Template bulan ini",
  "bc.simulatedNote": "{n} kontak simulasi menerimanya di simulator.",
  "bc.to": "Ke: {list}",
  "bc.preview": "Pratinjau",
  "bc.consentNote": "Hanya kontak yang setuju menerima broadcast dan belum STOP.",
  "bc.confirm": "Kirim \"{name}\" ke {n} kontak? Perkiraan biaya {cost}.",
  "bc.queued": "Broadcast diantrikan",
  "bc.campaigns": "Kampanye",
  "bc.name": "Nama",
  "bc.status": "Status",
  "bc.progress": "Terkirim / diterima / dibaca / gagal",
  "bc.created": "Dibuat",
  "bc.templates": "Template",
  "bc.sync": "Sinkron dari WhatsApp",
  "bc.synced": "{n} template disinkronkan",
  "bc.register": "Daftarkan manual",
  "bc.registerHint": "Harus sudah disetujui di WhatsApp Manager dengan nama dan bahasa yang sama.",
  "bc.registerButton": "Daftarkan",
  "bc.registered": "Template didaftarkan",
  "bc.noTemplates": "Belum ada template.",
  "bc.lang": "Bahasa",
  "bc.category": "Kategori",
  "bc.body": "Isi",
  "bc.contact": "Kontak",
  "bc.tries": "Coba",
  "bc.sent": "Terkirim",
  "bc.delivered": "Diterima",
  "bc.read": "Dibaca",
  "bc.failed": "Gagal",
  "bc.error": "Galat",

  // errors coming back from the API
  "err.Wrong email or password": "Email atau kata sandi salah",
  "err.Too many failed attempts. Try again in 15 minutes.": "Terlalu banyak percobaan. Coba lagi 15 menit lagi.",
  "err.This contact opted out (STOP). Messages can't be sent.": "Kontak ini sudah STOP. Pesan tidak bisa dikirim.",
  "err.Outside WhatsApp's 24-hour window: only approved templates can be sent.":
    "Di luar jendela 24 jam WhatsApp: hanya template yang bisa dikirim.",
  "err.Invalid code": "Kode salah",
  "err.Two-factor code required": "Masukkan kode 2FA",
  "err.Current password is wrong": "Kata sandi sekarang salah",
  "err.Reminders are for contacts on treatment": "Pengingat hanya untuk pasien yang sedang berobat",
  "err.Start the setup first": "Mulai pengaturan dulu",
  "err.Shortcut already exists": "Pintasan sudah dipakai",
  "err.Shortcut needs letters or numbers": "Pintasan perlu huruf atau angka",
  "err.No message from the contact to answer yet": "Belum ada pesan dari kontak untuk dibalas",
  "err.AI budget for this month is used up": "Anggaran AI bulan ini sudah habis",
};

const en: Record<string, string> = {
  "common.loading": "Loading…",
  "common.save": "Save",
  "common.saved": "Saved",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.add": "Add",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.search": "Search",
  "common.none": "None",
  "common.never": "never",
  "common.you": "you",
  "common.on": "on",
  "common.off": "off",
  "common.today": "Today",
  "common.thisMonth": "This month",
  "common.table": "Table",
  "common.chart": "Chart",
  "common.readOnly": "Read-only.",
  "common.simulated": "simulated",
  "common.theme": "Switch light / dark mode",
  "common.language": "Language",

  "time.justNow": "just now",
  "time.minutes": "{n}m",
  "time.hours": "{n}h",
  "time.days": "{n}d",
  "time.windowClosed": "window closed",
  "time.windowLeft": "{h}h {m}m left",

  "nav.conversations": "Conversations",
  "nav.outreach": "Outreach",
  "nav.reports": "Reports",
  "nav.admin": "Admin",
  "nav.inbox": "Inbox",
  "nav.cases": "Cases",
  "nav.contacts": "Contacts",
  "nav.simulator": "Simulator",
  "nav.broadcasts": "Broadcasts",
  "nav.dashboard": "Dashboard",
  "nav.audit": "Audit log",
  "nav.settings": "Settings",
  "nav.knowledge": "Knowledge",
  "nav.signOut": "Sign out",
  "nav.tagline": "TB companion",
  "role.admin": "Admin",
  "role.agent": "Agent",
  "role.reviewer": "Reviewer",

  "login.subtitle": "Staff sign-in",
  "login.email": "Email",
  "login.password": "Password",
  "login.submit": "Sign in",
  "login.submitting": "Signing in…",
  "login.prototype": "Prototype — test data only.",
  "login.code": "Verification code",
  "login.codeHint": "Open your authenticator app and enter the 6 digits.",
  "account.title": "My account",
  "account.twofa": "Two-step verification",
  "account.twofaOn": "On. Signing in needs a code from your authenticator app.",
  "account.twofaOff": "Off. Add a code from your phone at sign-in to protect the account.",
  "account.setup": "Turn on",
  "account.scan": "Scan this with Google Authenticator, Authy or a similar app, then enter the 6 digits it shows.",
  "account.manual": "Can't scan? Enter this key:",
  "account.confirm": "Confirm",
  "account.disable": "Turn off",
  "account.disableHint": "Enter your password to turn two-step verification off.",
  "account.password": "Change password",
  "account.current": "Current password",
  "account.new": "New password (10+)",
  "account.change": "Change",
  "account.changed": "Password changed. Other sessions were signed out.",
  "staff.reset2fa": "Reset",
  "staff.reset2faConfirm": "Turn off two-step verification for {name}? They can sign in with the password alone.",

  "channel.simulated": "sim",
  "sev.low": "Low",
  "sev.high": "High",
  "sev.emergency": "Emergency",
  "cat.emergency": "emergency",
  "cat.self_harm": "self-harm",
  "cat.adverse_drug": "drug side effects",
  "cat.adherence": "treatment stopped",
  "cat.budget": "AI budget",
  "cat.bot_error": "bot error",
  "cat.screening": "screening",
  "mode.human": "Staff handling",

  "inbox.searchPlaceholder": "Search",
  "inbox.allChannels": "All channels",
  "inbox.anyStatus": "Any status",
  "inbox.open": "Open",
  "inbox.resolved": "Resolved",
  "inbox.anyFlag": "Any flag",
  "inbox.flagged": "Flagged",
  "inbox.highUp": "High and above",
  "inbox.emergency": "Emergency",
  "inbox.botAndStaff": "Bot & staff",
  "inbox.bot": "Bot",
  "inbox.staffHandling": "Staff handling",
  "inbox.optedOut": "STOP",
  "inbox.empty": "No conversations.",
  "inbox.select": "Select a conversation",
  "inbox.filterChannel": "Channel",
  "inbox.filterStatus": "Status",
  "inbox.filterFlag": "Flag",
  "inbox.filterMode": "Mode",
  "inbox.filterLabel": "Label",
  "inbox.anyLabel": "Any label",

  "thread.assignedTo": "assigned to {name}",
  "thread.unassigned": "unassigned",
  "thread.bot": "Bot",
  "thread.staff": "Staff",
  "thread.modeHint": "Staff mode: the bot stays silent",
  "thread.summary": "AI summary",
  "thread.summarising": "Summarising…",
  "thread.assignMe": "Assign to me",
  "thread.resolve": "Resolve",
  "thread.reopen": "Reopen",
  "thread.replyPlaceholderBot": "Reply as staff (the bot will step back)",
  "thread.replyPlaceholder": "Reply as staff",
  "thread.notePlaceholder": "Internal note, never sent to the patient",
  "thread.send": "Send",
  "thread.addNote": "Save note",
  "thread.sendHint": "Ctrl+Enter to send · type / for saved replies",
  "thread.optedOut": "This contact replied STOP. Messages can't be sent.",
  "thread.tabReply": "Reply",
  "thread.tabNote": "Note",
  "thread.suggest": "AI suggestion",
  "thread.suggesting": "Drafting…",
  "thread.attach": "Attach a file",
  "thread.labels": "Labels",
  "thread.addLabel": "Add label",
  "summary.title": "Summary for takeover",
  "summary.footer": "AI-generated ({model}, {cost}). Check the thread before acting.",

  "msg.bot": "Onti (bot)",
  "msg.staff": "Staff",
  "msg.broadcast": "Broadcast",
  "msg.note": "Note",
  "msg.notDelivered": "Not delivered: {error}",
  "msg.flaggedBy": "Flagged by {reason}",
  "msg.sources": "Sources {docs}",
  "msg.tokens": "{n} tokens",
  "msg.transcript": "Transcript",
  "msg.openFile": "Open file",

  "contact.since": "Contact since {date}",
  "contact.details": "Details",
  "contact.phone": "Phone",
  "contact.messages": "Messages",
  "contact.active": "Active",
  "contact.optedOut": "Opted out",
  "contact.broadcasts": "Broadcasts",
  "contact.subscribed": "Subscribed",
  "contact.notSubscribed": "Not subscribed",
  "contact.channels": "Channels",
  "contact.cases": "Cases",
  "contact.noCases": "No cases.",
  "contact.notes": "Notes",
  "contact.journey": "Patient journey",
  "contact.treatmentMonth": "Treatment month {n}",

  "cases.filterActive": "Open and claimed",
  "cases.filterOpen": "Unclaimed",
  "cases.filterClaimed": "Claimed",
  "cases.filterResolved": "Resolved",
  "cases.filterAll": "All cases",
  "cases.status.OPEN": "Unclaimed",
  "cases.status.CLAIMED": "Claimed",
  "cases.status.RESOLVED": "Resolved",
  "cases.empty": "No cases.",
  "cases.select": "Select a case",
  "cases.title": "Case #{id}",
  "cases.opened": "opened {date}",
  "cases.openConversation": "Open conversation",
  "cases.claim": "Claim",
  "cases.unclaim": "Unclaim",
  "cases.resolveKeep": "Resolve, keep staff mode",
  "cases.resolveBot": "Resolve & return to bot",
  "cases.contact": "Contact",
  "cases.channel": "Channel",
  "cases.assigned": "Assigned to",
  "cases.nobody": "Nobody yet",
  "cases.mode": "Mode",
  "cases.trigger": "Message that raised it",
  "cases.notes": "Notes",
  "cases.noNotes": "No notes yet.",
  "cases.notePlaceholder": "Add a note",
  "cases.addNote": "Add",

  "contacts.search": "Search name, phone or id",
  "contacts.timeline": "All messages across channels",
  "contacts.openConversation": "Open {channel} conversation",
  "contacts.consent": "Consent",
  "contacts.recordConsent": "Record broadcast consent",
  "contacts.revokeConsent": "Revoke broadcast consent",
  "contacts.consentRecorded": "Consent recorded",
  "contacts.notesPlaceholder": "Notes about this contact",
  "contacts.saveNotes": "Save notes",
  "contacts.merge": "Merge a duplicate",
  "contacts.chooseContact": "Choose a contact",
  "contacts.mergeButton": "Merge",
  "contacts.mergeHint": "Channels, conversations, cases and consents move here.",
  "contacts.merged": "Contacts merged",
  "contacts.select": "Select a contact",
  "contacts.subscribed": "subscribed",
  "contacts.optedOut": "STOP",

  "sim.intro": "Chat as a test user. Nothing is sent to Meta.",
  "sim.channel": "Channel",
  "sim.userId": "User id",
  "sim.name": "Display name",
  "sim.quick": "Quick messages",
  "sim.empty": "Send a message to start.",
  "sim.placeholder": "Type as the user…",
  "sim.openInbox": "Open in inbox →",
  "sim.staffNotice": "Staff is handling this chat, so the bot stays silent.",
  "sim.handBack": "Hand back to bot",
  "sim.s.normal": "Normal question",
  "sim.s.english": "English question",
  "sim.s.mild": "Mild side effect",
  "sim.s.drug": "Serious side effect",
  "sim.s.emergency": "Emergency",
  "sim.s.selfharm": "Self-harm",
  "sim.s.adherence": "Stopping treatment",
  "sim.s.screening": "TB screening",
  "sim.s.subscribe": "Subscribe (LANGGANAN)",
  "sim.s.stop": "Opt out (STOP)",
  "sim.s.start": "Opt back in (MULAI)",
  "sim.staff": "Staff",
  "sim.record": "Record a voice note",
  "sim.stopRecording": "Stop & send",
  "sim.recording": "Recording…",
  "sim.micDenied": "The microphone isn't available in this browser.",

  "dash.convToday": "Conversations today",
  "dash.thisMonth": "{n} this month",
  "dash.firstBot": "First response · bot",
  "dash.firstStaff": "First response · staff",
  "dash.replies": "{n} replies · 30 days",
  "dash.contacts": "Contacts",
  "dash.contactsSub": "{sub} subscribed · {out} opted out",
  "dash.caseEmergency": "Emergency cases",
  "dash.caseHigh": "High cases",
  "dash.caseLow": "Low cases",
  "dash.costs": "Costs this month",
  "dash.aiSpend": "AI spend",
  "dash.noLimit": "no limit",
  "dash.ok": "Within limit",
  "dash.warn": "Approaching limit",
  "dash.over": "Limit reached",
  "dash.calls": "{n} AI calls · {failed} failed",
  "dash.fallbackModel": "at 100%: cheaper model",
  "dash.fallbackFixed": "at 100%: fixed reply",
  "dash.waTemplates": "WhatsApp templates",
  "dash.waSent": "{n} WhatsApp messages sent",
  "dash.byChannel": "Active conversations by channel",
  "dash.conversations": "{n} conversations",
  "dash.programme": "TB programme",
  "dash.flagsWeek": "Risk flags, 8 weeks",
  "dash.adherence": "Medication adherence",
  "dash.adherenceSub": "{taken} of {total} reminders answered as taken · 30 days",
  "dash.journey": "Patient stages",
  "dash.screenings": "Screenings",
  "dash.screeningsSub": "{n} advised to get tested · 30 days",
  "dash.export": "Download CSV",

  "settings.channels": "Channels",
  "settings.botSafety": "Bot, safety & costs",
  "settings.staff": "Staff",
  "settings.replies": "Saved replies",
  "settings.labels": "Labels",
  "settings.hours": "Office hours",
  "settings.security": "Account security",
  "ch.connected": "Connected",
  "ch.notConfigured": "Not configured",
  "ch.off": "Off",
  "ch.webhook": "Webhook",
  "ch.missing": "Missing: {list}",
  "ch.learned": "{key} from webhook: {value}",
  "ch.lastWebhook": "Last webhook: {when}",
  "ch.test": "Test token",
  "ch.checking": "Checking…",
  "ch.tokenOk": "Token works: {phone}. Sending: {sending}",
  "ch.failed": "Failed: {error}",
  "ch.llm": "LLM",
  "ch.answers": "Answers",
  "ch.classifier": "Classifier",
  "ch.email": "Email alerts",
  "ed.unsaved": "Unsaved changes",
  "ed.saved": "All changes saved",
  "ed.reset": "Reset to default",
  "ed.rules": "Safety keywords",
  "ed.rulesHint": "One word or phrase per line. Always on.",
  "ed.group.Bot": "Bot",
  "ed.group.Safety": "Safety",
  "ed.group.Consent & keywords": "Consent & keywords",
  "ed.group.Limits & budget": "Limits & budget",
  "ed.group.WhatsApp pricing": "WhatsApp pricing",
  "ed.group.Office hours": "Office hours",
  "ed.group.Reminders": "Medication reminders",
  "staff.email": "Email",
  "staff.name": "Name",
  "staff.role": "Role",
  "staff.status": "Status",
  "staff.deactivate": "Deactivate",
  "staff.activate": "Activate",
  "staff.add": "Add staff",
  "staff.password": "Password (10+)",
  "staff.added": "Staff member added",
  "staff.roleUpdated": "Role updated",
  "staff.twofa": "2FA",
  "ed.discard": "Discard",
  "day.1": "Mon",
  "day.2": "Tue",
  "day.3": "Wed",
  "day.4": "Thu",
  "day.5": "Fri",
  "day.6": "Sat",
  "day.7": "Sun",
  "set.away_message.hint": "{hours} becomes the office hours.",
  "ed.language": "Language version",
  "set.persona_prompt": "Bot instructions (persona)",
  "set.model_answer": "Answer model",
  "set.model_classifier": "Classifier model",
  "set.history_turns": "Chat history read",
  "set.retrieval_k": "Knowledge passages",
  "set.max_input_chars": "Max incoming characters",
  "set.max_output_tokens": "Max answer tokens",
  "set.max_reply_chars": "Max reply characters",
  "set.classifier_enabled": "AI risk classifier",
  "set.safety_emergency": "Emergency reply",
  "set.safety_self_harm": "Self-harm reply",
  "set.safety_adverse_drug": "Side-effect reply",
  "set.safety_adherence": "Stopping-treatment reply",
  "set.safety_other": "Other high-risk reply",
  "set.consent_notice": "Privacy notice (first message)",
  "set.optout_confirm": "STOP confirmation",
  "set.optin_confirm": "MULAI confirmation",
  "set.subscribe_confirm": "LANGGANAN confirmation",
  "set.non_text_reply": "Reply to photos/stickers",
  "set.monthly_budget_idr": "Monthly AI budget (Rp)",
  "set.budget_alert_ratio": "Budget alert at (0–1)",
  "set.budget_fallback_mode": "When the budget runs out",
  "set.budget_fallback_reply": "Fixed reply (budget out / bot error)",
  "set.daily_message_cap": "Bot replies per contact per day",
  "set.daily_cap_reply": "Daily cap reply",
  "set.rate_limit_count": "Burst message limit",
  "set.rate_limit_window_minutes": "Within (minutes)",
  "set.rate_limit_reply": "Too-fast reply",
  "set.wa_rate_marketing_idr": "Marketing template rate (Rp)",
  "set.wa_rate_utility_idr": "Utility template rate (Rp)",
  "set.wa_free_tier_messages": "Free messages per month",
  "set.office_hours_enabled": "Use office hours",
  "set.office_days": "Working days",
  "set.office_open": "Opens",
  "set.office_close": "Closes",
  "set.away_message": "Out-of-hours message",
  "set.reminder_enabled": "Send medication reminders",
  "set.reminder_time": "Default reminder time",
  "set.reminder_text": "Reminder text",
  "set.reminder_template": "WhatsApp template (outside 24h)",
  "set.missed_followup_hours": "Follow up if unanswered (hours)",
  "set.missed_case_after": "Open a case after missed (times)",
  "set.missed_followup": "Missed-dose follow-up message",
  "set.transcribe_voice": "Transcribe voice notes",
  "choice.classifier_model": "Use a cheaper model",
  "choice.fixed_reply": "Fixed reply + case",
  "replies.shortcut": "Shortcut",
  "replies.title": "Title",
  "replies.body": "Reply text",
  "replies.hint": "Type / in the reply box to use one. {nama} becomes the contact's name.",
  "replies.empty": "No saved replies yet.",
  "replies.add": "Add reply",
  "labels.placeholder": "New label name",
  "labels.empty": "No labels yet.",
  "labels.deleteConfirm": "Remove label \"{name}\" from every conversation?",

  "kb.articles": "Articles",
  "kb.gaps": "Unanswered",
  "kb.new": "New article",
  "kb.hidden": "hidden",
  "kb.visible": "Used by the bot",
  "kb.titlePlaceholder": "Article title",
  "kb.hint": "The first paragraph is the summary. Use ## for subheadings.",
  "kb.deleteConfirm": "Delete article \"{title}\"?",
  "kb.pending": "Unpublished changes",
  "kb.updating": "Updating the bot's knowledge…",
  "kb.upToDate": "Published {date}",
  "kb.failed": "Update failed: {error}",
  "kb.publish": "Publish",
  "kb.gapsIntro": "Questions the bot couldn't answer from the articles. Add the answer to an article, then mark it done.",
  "kb.noGaps": "No unanswered questions.",
  "kb.done": "Done",
  "kb.ignore": "Ignore",

  "nav.patients": "Patients",
  "nav.tasks": "Tasks",
  "stage.none": "Not a patient",
  "stage.suspect": "Presumptive",
  "stage.testing": "Testing",
  "stage.treatment": "On treatment",
  "stage.completed": "Completed",
  "stage.lost": "Lost to follow-up",
  "journey.title": "Patient journey",
  "journey.stage": "Stage",
  "journey.month": "Month {n} of {total}",
  "journey.start": "Treatment start",
  "journey.months": "Length (months)",
  "journey.puskesmas": "Puskesmas",
  "journey.kader": "Kader",
  "journey.none": "None yet",
  "journey.reminder": "Medication reminder",
  "journey.last14": "Medicine, last 14 days",
  "journey.taken": "Taken",
  "journey.missed": "Missed",
  "journey.noReply": "No data",
  "journey.tasks": "Tasks",
  "board.empty": "No patients yet. Set a stage from the contact panel in the inbox or the Contacts page.",
  "board.week": "{taken}/{total} taken this week",
  "board.tasks": "{n} tasks",
  "board.month": "Month {n}",
  "tasks.mine": "My tasks",
  "tasks.all": "All",
  "tasks.done": "Done",
  "tasks.overdue": "Overdue",
  "tasks.today": "Today",
  "tasks.upcoming": "Upcoming",
  "tasks.noDate": "No date",
  "tasks.empty": "No tasks.",
  "tasks.new": "New task",
  "tasks.titlePlaceholder": "What needs doing?",
  "tasks.kind.call": "Call",
  "tasks.kind.visit": "Home visit",
  "tasks.kind.other": "Other",
  "tasks.due": "Due",
  "tasks.assignee": "For",
  "tasks.unassigned": "Unassigned",
  "tasks.complete": "Done",
  "tasks.outcome": "Outcome? (optional)",
  "tasks.add": "Add",
  "tasks.auto": "automatic",
  "tasks.reopen": "Reopen",
  "tasks.contact": "Contact (optional)",
  "set.reminder_taken": "Reply when taken",
  "set.reminder_missed": "Reply when not yet taken",
  "set.reminder_text.hint": "{name} becomes the contact's first name. Sudah / Belum buttons are added automatically.",
  "set.reminder_template.hint": "Approved WhatsApp template name, for patients who haven't chatted in 24 hours. Empty = that day is skipped.",

  "audit.intro": "Who viewed, replied, changed or sent what.",
  "audit.all": "All actions",
  "audit.when": "When",
  "audit.who": "Who",
  "audit.action": "Action",
  "audit.target": "Target",
  "audit.details": "Details",

  "bc.new": "New broadcast",
  "bc.template": "Template",
  "bc.chooseTemplate": "Choose an approved template",
  "bc.varHint": "text, or {{name}} for the contact's name",
  "bc.campaignName": "Campaign name",
  "bc.estimate": "Estimate cost",
  "bc.sendTo": "Send to {n}",
  "bc.recipients": "Recipients",
  "bc.cost": "Estimated cost",
  "bc.rate": "{cat} rate",
  "bc.thisMonth": "Templates this month",
  "bc.simulatedNote": "{n} simulated contacts get it in the simulator.",
  "bc.to": "To: {list}",
  "bc.preview": "Preview",
  "bc.consentNote": "Only contacts who agreed to broadcasts and haven't sent STOP.",
  "bc.confirm": "Send \"{name}\" to {n} contacts? Estimated cost {cost}.",
  "bc.queued": "Broadcast queued",
  "bc.campaigns": "Campaigns",
  "bc.name": "Name",
  "bc.status": "Status",
  "bc.progress": "Sent / delivered / read / failed",
  "bc.created": "Created",
  "bc.templates": "Templates",
  "bc.sync": "Sync from WhatsApp",
  "bc.synced": "Synced {n} templates",
  "bc.register": "Register manually",
  "bc.registerHint": "It must already be approved in WhatsApp Manager under the same name and language.",
  "bc.registerButton": "Register",
  "bc.registered": "Template registered",
  "bc.noTemplates": "No templates yet.",
  "bc.lang": "Lang",
  "bc.category": "Category",
  "bc.body": "Body",
  "bc.contact": "Contact",
  "bc.tries": "Tries",
  "bc.sent": "Sent",
  "bc.delivered": "Delivered",
  "bc.read": "Read",
  "bc.failed": "Failed",
  "bc.error": "Error",
};

export const dict: Record<Lang, Record<string, string>> = { id, en };
