"""whatsapp templates and broadcasts

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 15:15:19.879829
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('variable_count', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'language', name='uq_template_name_lang')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('rate_idr', sa.Float(), nullable=False),
    sa.Column('est_cost_idr', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['wa_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['contact_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'contact_id', name='uq_bc_recipient')
    )
    with op.batch_alter_table('broadcast_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_recipients_broadcast_id'), ['broadcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_recipients_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_recipients_external_id'))
        batch_op.drop_index(batch_op.f('ix_broadcast_recipients_broadcast_id'))

    op.drop_table('broadcast_recipients')
    op.drop_table('broadcasts')
    op.drop_table('wa_templates')
    # ### end Alembic commands ###
